version: '3.4'
services:

  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: estudos-docker
    ports:
      - "3308:3306"
    networks:
      - lagrota-network

  aplicacao-docker-estudos:
    image: gabriellagrota/estudos
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/estudos-docker?useSSL=false&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: docker
    ports:
      - "8030:8030"
    command: ./wait-for-it.sh db:3306 -- mvn spring-boot:run
    depends_on:
      - db
    networks:
      - lagrota-network

networks:
  lagrota-network:
    driver: bridge