spring:
  application:
    name: pessoa

  datasource:
    url: jdbc:mysql://localhost:3306/estudos-docker?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8030