name: Continous Integration with Github Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build application jar
#      working-directory: ./docker
      run: mvn clean package

    - name: Docker compose build
#      working-directory: ./docker
      run: docker compose build

    - name: Push do Docker hub Container Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/estudos:latest ${{ secrets.DOCKER_USERNAME }}/estudos:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/estudos:${{ github.run_id }}
                docker push ${{ secrets.DOCKER_USERNAME }}/estudos:latest